# Generated by Django 2.1.7 on 2019-03-16 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('producer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mer_number', models.CharField(max_length=200)),
                ('mer_name', models.CharField(max_length=200)),
                ('mer_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Merchandise'),
        ),
    ]
